BOARD = ".board"
BOARD_FLIPPED = ".board.flipped"
RESIGN = "//*[contains(@class, 'resign') or contains(text(), 'Resign')]"
NODES = ".node"
NODE_SELECTED = ".node.selected"
PROMOTION_PIECE = ".promotion-piece"
FIGURINE_SPAN = ".icon-font-chess"
